#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Disable concurrent to run tasks sequentially
# npx lint-staged --concurrent false

# Temporarily disabled for deployment
echo "Skipping lint-staged for deployment"